"""Test the whole commits workflow script."""

import pytest
import json
import pandas as pd

from githubanalysis.processing.get_all_branches_commits import AllBranchesCommitsGetter

# def test_function():
#     # Arrange:

#     # Act:

#     # Assert:

rawjson = "tests/testdata/raw-commits__all-branches-commits_FlicAnderson-peramagroon_2024-10-17.json"
deduplicatedjson = "tests/testdata/deduplicated-commits__all-branches-commits_FlicAnderson-peramagroon_2024-10-17_deduplicated.json"
processed_csv = "tests/testdata/processed-csv__processed-commits_FlicAnderson-peramagroon_2024-10-17.csv"
commit_details = "tests/testdata/commit-details__commits_changes_FlicAnderson-peramagroon_2024-10-17.csv"
workflow_outputs = "tests/testdata/workflow-outputs__commits_cats_stats_FlicAnderson-peramagroon_2024-10-17.csv"


def read_in_csv_file(filename: str) -> pd.DataFrame:
    return pd.read_csv(filename, index_col=0, header=0)


def get_number_commits_in_dict(d: dict[str, list[str]]) -> int:
    return sum([len(d[x]) for x in d if isinstance(d[x], list)])


def test_outputs_read_in_match():
    # Arrange:

    processed_csv_df = read_in_csv_file(processed_csv)
    commit_details_df = read_in_csv_file(commit_details)
    workflow_outputs_df = read_in_csv_file(workflow_outputs)
    assert (
        len(processed_csv_df) == len(commit_details_df) == len(workflow_outputs_df)
    ), "WARNING: The test output files are not of same length. This could be due to intentionally dropped NAs. "

    allbranchescommitsgetter = AllBranchesCommitsGetter(
        repo_name="FlicAnderson/peramagroon",
        in_notebook=False,
        config_path="githubanalysis/config.cfg",
        logger=None,
    )

    # Act:
    output_get_all_branches_commits = allbranchescommitsgetter.get_all_branches_commits(
        repo_name="FlicAnderson/peramagroon"
    )

    # Assert:
    assert (  # output matches read-in number of processed commits csv rows
        (get_number_commits_in_dict(output_get_all_branches_commits))
        == len(processed_csv_df.index)
    ), f"Length of values in dict generated by get_all_branches_commits() ({get_number_commits_in_dict(output_get_all_branches_commits)}) does not match number of rows read in from processed-csv .csv file ({len(processed_csv_df.index)})"

    # Assert:
    assert (  # output matches read-in number of workflow outputs csv rows
        (get_number_commits_in_dict(output_get_all_branches_commits))
        == len(workflow_outputs_df.index)
    ), f"Length of values in dict generated by get_all_branches_commits() ({get_number_commits_in_dict(output_get_all_branches_commits)}) does not match number of rows read in from workflow outputs .csv file ({len(processed_csv_df.index)}. This COULD be due to intentionally dropped NAs - check carefully to ensure this is as expected.)"


def test_output_generated(repo_name="FlicAnderson/peramagroon"):
    """
    Test that for a valid repo_name, a final .csv file is generated by the commits_workflow.

    TODO
    """
    # Arrange:

    # Act:

    # Assert:
    pass
