"""Testing for core commits-grab code."""

import pytest
import json

from githubanalysis.processing.get_all_branches_commits import AllBranchesCommitsGetter

# def test_get_all_branches_commits():
#     # Arrange:

#     # Act:

#     # Assert:

rawjson = "tests/testdata/raw-commits__all-branches-commits_FlicAnderson-peramagroon_2024-10-17.json"
deduplicatedjson = "tests/testdata/deduplicated-commits__all-branches-commits_FlicAnderson-peramagroon_2024-10-17_deduplicated.json"


def setup_raw_data(rawjson: str) -> dict:
    with open(rawjson) as f1:
        rawjsondata = json.load(f1)
        f1.close
    assert isinstance(
        rawjsondata, dict
    ), f"Error reading in testdata for raw .json file: {rawjson}"
    assert (
        len(rawjsondata.keys()) == 2
    ), "Issue with expected raw json dataset: repo FlicAnderson/peramagroon should have two branches, therefore 2 dict keys"
    return rawjsondata


def setup_deduplicated_data(deduplicatedjson: str) -> dict:
    with open(deduplicatedjson) as f2:
        deduplicatedjsondata = json.load(f2)
        f2.close
    assert isinstance(
        deduplicatedjsondata, dict
    ), f"Error reading in testdata for deduplicated .json file: {deduplicatedjson}"
    return deduplicatedjsondata


@pytest.mark.xfail(reason="Fails remotely: relies on GH config file")
def test_get_all_branches_commits_N_branches():
    #     # Arrange:
    expectedrawjson = setup_raw_data(rawjson)
    expecteddeduplicatedjson = setup_deduplicated_data(deduplicatedjson)
    allbranchescommitsgetter = AllBranchesCommitsGetter(
        repo_name="FlicAnderson/peramagroon",
        in_notebook=False,
        config_path="githubanalysis/config.cfg",
        logger=None,
    )
    # Act:
    output_get_all_branches_commits = allbranchescommitsgetter.get_all_branches_commits(
        repo_name="FlicAnderson/peramagroon"
    )
    # Assert:
    assert (
        len(expectedrawjson) == len(output_get_all_branches_commits)
    ), f"The length of branches reading in RAW json {rawjson} and number of branches in output generated by running get_all_branches_commits() on test repo 'FlicAnderson/peramagroon' are different. Check this!"
    assert (
        len(expecteddeduplicatedjson) == len(output_get_all_branches_commits)
    ), f"The length of branches reading in deduplicated json {deduplicatedjson} and length of output (number of branches) generated by running get_all_branches_commits() on test repo 'FlicAnderson/peramagroon' are different. Check this!"
