from logging import Logger
from pathlib import Path
import itertools

from githubanalysis.setup_classes import LocationSetup

# import utilities.get_default_logger as loggit


class Globber(LocationSetup):
    def _log_name(self) -> str:
        return "glob_making_matching"

    def __init__(self, in_notebook: bool, logger: None | Logger = None) -> None:
        super().__init__(in_notebook, logger)

    def flatten(self, list_of_lists):
        # This code unnests the list of lists generated by the code I wrote which uses pathlib and glob to match filenames.
        # NOTE: while fixing the code to avoid returning nested lists would be the better option, it will take longer, so I'm leaving this as a TODO.
        # via: https://stackoverflow.com/a/1077074
        return list(itertools.chain.from_iterable(list_of_lists))

    # function creating filename globs to match for both main- and sub- reviews:
    def filename_glob_maker(
        self, repo_name: str, out_filename: str, matchstrings: list[str]
    ) -> list[str]:
        """
        # takes single repo_name (string) e.g. "FlicAnderson/PR_test"
        # takes front part of filename (string) e.g. "all-PR-reviews_json"
        # takes review-type-specific format string (string) e.g. ["_main-reviews__", "_sub-reviews__"]

        # returns globs for that reponame as string
        """
        filename_repo_globs = []

        sanitised_repo_name = repo_name.replace("/", "-")

        for matchentry in matchstrings:
            filename_repo_globs.append(
                f"{out_filename}{matchentry}{sanitised_repo_name}_"
            )

        return filename_repo_globs

    def multi_repo_filename_glob_maker(
        self, subset_repos: list[str], out_filename: str, matchstrings: list[str]
    ) -> list[str]:

        # for multiple repos:

        output_globs = []

        self.logger.debug(f"{subset_repos=}")  # for clarity of what's running here:

        for reponame in subset_repos:  # (currently 2x repos)
            output_globs.extend(
                self.filename_glob_maker(
                    repo_name=reponame,
                    out_filename=out_filename,
                    matchstrings=matchstrings,
                )
            )
        self.logger.debug(
            f"{output_globs=}"
        )  # return item now contains multiple repos' globs :D

        return output_globs

    def multi_repo_filename_file_matcher(
        self,
        list_of_repos_to_match: list[str],
        out_filename: str,
        matchstrings: list[str],
        file_extension: str,
    ) -> list[Path]:
        """
        This function runs through a list of repo_names and generates
        filename globs for each repo_name, based on an intial filename
        prefix, and subsequent matchstrings.

        It writes out messages regarding non-matched expected globs, and
        returns the list of actual filepaths matched to the generated strings.
        """
        assert isinstance(list_of_repos_to_match, list)
        matching_files = []
        assert file_extension in [".csv", ".json"], (
            "File extension must be one of '.csv' or '.json' - please check this is correct."
        )

        # run glob generator for multirepos:
        multi_glob = self.multi_repo_filename_glob_maker(
            subset_repos=list_of_repos_to_match,
            out_filename=out_filename,
            matchstrings=matchstrings,
        )

        # actually match the globs against filesystem:
        matching_files = []
        non_matching_globs = []

        for fileglob in multi_glob:
            # self.logger.info(fileglob)
            filename_file_glob = f"{fileglob}*{file_extension}"
            interaction_data_location = self.data_location
            matching_files.append(
                list(interaction_data_location.glob(filename_file_glob))
            )  # non-recursive matching search with path objects returned.
            if (
                len(list(interaction_data_location.glob(filename_file_glob))) == 0
            ):  # handle non-matched globs into list for counting and printing/warning
                non_matching_globs.append(filename_file_glob)

        matching_files = self.flatten(matching_files)

        self.logger.info(f"{len(multi_glob)} glob strings generated")
        self.logger.info(
            f"{len(matching_files)} matching files for {len(list_of_repos_to_match)} repos in list"
        )
        self.logger.info(
            f"Number of expected files to matched files matches 1:1? {len(multi_glob) == len(matching_files)}"
        )

        self.logger.warning(f"There are {len(non_matching_globs)} non-matched globs")
        self.logger.warning(f"{non_matching_globs =}")

        return matching_files
