"""Workflow for running PR Code Review (PRCR) processing and analysis code for 1 repo."""

import logging
import pandas as pd
from pathlib import Path
import re
import os
import itertools

from githubanalysis.setup_classes import LocationSetup
import utilities.get_default_logger as loggit
from githubanalysis.processing.get_all_PR_code_reviews import GetCodeReviews
from githubanalysis.processing.reformat_PR_reviews import ReviewsFormatter


def flatten(list_of_lists):
    # This code unnests the list of lists generated by the code I wrote which uses pathlib and glob to match filenames.
    # NOTE: while fixing the code to avoid returning nested lists would be the better option, it will take longer, so I'm leaving this as a TODO.
    # via: https://stackoverflow.com/a/1077074
    return list(itertools.chain.from_iterable(list_of_lists))


class RunPRReviews(LocationSetup):
    # repo_name: str | None

    def _log_name(self) -> str:
        return "reviews_workflow_logs"

    def __init__(
        self,
        config_path: str,
        in_notebook: bool,
        logger: None | logging.Logger = None,
        out_filename: str = "processed-PR-reviews",
    ) -> None:
        super().__init__(in_notebook=in_notebook, logger=logger)
        self.config_path = config_path
        self.repo_name = None
        self.out_filename = out_filename

    def run_get_reviews(self, filepath: Path):
        """
        This uses code from get_all_PR_code_reviews.py to run on a list
        of repo_names.

        NOTE:
        For Flic's PhD work data collection was done via running
        get_all_PR_code_reviews.py from commandline and using the main()
        version in that script.
        This function pulls that code across to the workflow script for
        the convenience of future users and easier understanding of the
        intended workflow.
        """

        get_code_reviews = GetCodeReviews(
            repo_name="",  # empty string currently as we're providing a LIST of repos for get_code_reviews.get_repos() then iterating through!
            config_path=self.config_path,
            in_notebook=self.in_notebook,
            logger=self.logger,
        )

        assert filepath is not None, (
            "You must provide a filepath for the repo names list file, e.g. 'data/code_review_subset_2025-05-30_x16.txt'. "
        )

        filepath = Path(filepath)
        get_code_reviews.logger.info(f"reading repo names from file: {filepath}")
        repo_list = get_code_reviews.get_repos(repo_list_file_name=filepath)

        # loop through repo_list
        get_code_reviews.logger.info(
            f"Attempting to run through {len(repo_list)} repositories."
        )
        get_code_reviews.logger.info(f"{repo_list = }")

        get_code_reviews.logger.info("Getting DISCUSSION info for all repos:")
        # for each repo in repo_list, do all the things to get DISCUSSIONS FIRST:
        get_code_reviews.loop_over_repos(repo_list=repo_list, get_type="discussions")
        get_code_reviews.logger.info("Completed getting DISCUSSION info for all repos.")

        # then get CODE REVIEW content:
        get_code_reviews.logger.info("Getting CODE REVIEW info for all repos:")
        get_code_reviews.loop_over_repos(repo_list=repo_list, get_type="code-reviews")
        get_code_reviews.logger.info(
            "Completed getting CODE REVIEW info for all repos."
        )

        self.logger.info("Get discussions and code reviews info complete")

    ## UPDATE: This^ isn't necessary currently, as all the data-collection runs
    # were done by directly running get_all_PR_code_reviews.py as main
    # which takes commandline input of repo names list file and loops
    # over repos and gathered all the API content required for issue
    # ticket discussion interactions AND PR code review interactions.

    # function creating filename globs to match for both main- and sub- reviews:
    def PRCR_glob_maker(
        self, repo_name: str, out_filename: str, matchstrings: list[str]
    ) -> list[str]:
        """
        # takes single repo_name (string) e.g. "FlicAnderson/PR_test"
        # takes front part of filename (string) e.g. "all-PR-reviews_json"
        # takes review-type-specific format string (string) e.g. ["_main-reviews__", "_sub-reviews__"]

        # returns globs for that reponame as string
        """
        PRCR_repo_globs = []

        sanitised_repo_name = repo_name.replace("/", "-")

        for matchentry in matchstrings:
            PRCR_repo_globs.append(f"{out_filename}{matchentry}{sanitised_repo_name}_")

        return PRCR_repo_globs

    def multi_repo_PRCR_glob_maker(
        self, subset_repos: list[str], out_filename: str, matchstrings: list[str]
    ) -> list[str]:

        # for multiple repos:

        output_globs = []

        self.logger.info(f"{subset_repos=}")  # for clarity of what's running here:

        for reponame in subset_repos:  # (currently 2x repos)
            output_globs.extend(
                self.PRCR_glob_maker(
                    repo_name=reponame,
                    out_filename=out_filename,
                    matchstrings=matchstrings,
                )
            )
        self.logger.info(
            f"{output_globs=}"
        )  # return item now contains multiple repos' globs :D

        return output_globs

    def multi_repo_PRCR_file_matcher(
        self,
        list_of_repos_to_match: list[str],
        out_filename: str,
        matchstrings: list[str],
        file_extension: str,
    ) -> list[str | Path]:
        """
        This function runs through a list of repo_names and generates
        filename globs for each repo_name, based on an intial filename
        prefix, and subsequent matchstrings.

        It writes out messages regarding non-matched expected globs, and
        returns the list of actual filepaths matched to the generated strings.
        """
        assert isinstance(list_of_repos_to_match, list)
        matching_files = []
        assert file_extension in [".csv", ".json"], (
            "File extension must be one of '.csv' or '.json' - please check this is correct."
        )

        # run glob generator for multirepos:
        multi_glob = self.multi_repo_PRCR_glob_maker(
            subset_repos=list_of_repos_to_match,
            out_filename=out_filename,
            matchstrings=matchstrings,
        )

        # actually match the globs against filesystem:
        matching_files = []
        non_matching_globs = []

        for fileglob in multi_glob:
            # self.logger.info(fileglob)
            PRCR_file_glob = f"{fileglob}*{file_extension}"
            PR_data_location = (
                self.data_location
            )  # Path("../../data")  # == pathlib.Path(self.data_location)
            matching_files.append(
                list(PR_data_location.glob(PRCR_file_glob))
            )  # non-recursive matching search with path objects returned.
            if (
                len(list(PR_data_location.glob(PRCR_file_glob))) == 0
            ):  # handle non-matched globs into list for counting and printing/warning
                non_matching_globs.append(PRCR_file_glob)

        matching_files = flatten(matching_files)

        self.logger.info(f"{len(multi_glob)} glob strings generated")
        self.logger.info(
            f"{len(matching_files)} matching files for {len(list_of_repos_to_match)} repos in list"
        )
        self.logger.info(
            f"Number of expected files to matched files matches 1:1? {len(multi_glob) == len(matching_files)}"
        )

        self.logger.warning(f"There are {len(non_matching_globs)} non-matched globs")
        self.logger.warning(f"{non_matching_globs =}")

        return matching_files

    def review_sorter(
        self,
        file_to_sort: Path,
    ) -> str:
        rev_file_type = ""
        if file_to_sort.match("all-PR-reviews_json_sub-reviews*"):
            rev_file_type = "sub"
        elif file_to_sort.match("all-PR-reviews_json_main-reviews*"):
            rev_file_type = "main"
        elif file_to_sort.match("PR-issue-discussions*"):
            rev_file_type = "discussions"
        return rev_file_type

    def process_format_PR_reviews(
        self,
        reviews_file: Path,
        writeout: bool = True,
        out_filename: str = "processed-PR-reviews",
    ):
        """
        Process and format PR_reviews (ie output of
        get_all_PR_code_reviews() for a repo) into a dataframe.
        """
        # match the type of review from the filename
        reviews_type = self.review_sorter(file_to_sort=reviews_file)

        self.logger.info(
            f"Processing PR {reviews_type} reviews data from file {reviews_file}"
        )

        assert reviews_type in ["sub", "main", "discussions"], (
            "'reviews_type' must be one of 'sub' or 'main' or 'discussions' for correct handling."
        )

        reformat_PR_reviews = ReviewsFormatter(
            in_notebook=self.in_notebook,
        )
        reformatted_PR_reviews = reformat_PR_reviews.reformat_PR_reviews_object(
            PR_reviews_file=reviews_file, reviews_type=reviews_type
        )
        self.logger.info(
            f"did reformat {reviews_type} PR_reviews, created df of shape {reformatted_PR_reviews.shape if reformatted_PR_reviews is not None else 'No shape'} for repo {reformat_PR_reviews.repo_name}."
        )

        self.repo_name = reformat_PR_reviews.repo_name

        if writeout:
            reformat_PR_reviews.save_formatted_PR_reviews(
                out_filename=out_filename, reviews_type=reviews_type
            )
            self.logger.info(f"saved out reformat {reviews_type} PR_reviews")

        return reformat_PR_reviews.reformatted_PR_reviews

    def format_many_repo_PR_reviews(
        self,
        subset_repos_file: None | Path | str = None,
    ):
        """
        Look in the initialised data location (default: data/) and
        pull out all files matching out_filename prefix (default: "processed-PR-reviews_"),
        then run process_format_PR_reviews() on them.
        """

        if subset_repos_file is None:
            assert False, "TODO: handle this properly"
            # self.logger.info(
            #     f"No subset_repos_file provided, so will attempt formatting of ALL reviews files in {self.data_location}"
            # )
            # review_files = [
            #     f
            #     for f in os.listdir(self.data_location)
            #     if re.match(
            #         rf"({re.escape(self.out_filename)}).*(.csv)", f, re.IGNORECASE
            #     )
            # ]  # this is a list comprehension, just split over 3 lines ^
            # repolist = review_files
            # self.logger.info("{repolist}")

            # print(
            #     f"Currently processing {len(review_files)} review files' worth of PR Reviews data"
            # )

        else:
            assert isinstance(subset_repos_file, (str, Path)), (
                f"subset_repos_file is neither string nor Path object; {type(subset_repos_file)}"
            )
            # all_review_files_repos = [
            #     f
            #     for f in os.listdir(self.data_location)
            #     if re.match(
            #         rf"({re.escape(self.out_filename)}).*(.csv)", f, re.IGNORECASE
            #     )
            # ]  # this is a list comprehension, just split over 3 lines ^
            # self.logger.info("{repolist}")

            with open(subset_repos_file, "r") as f:
                subset_repos = [txtline.strip() for txtline in f.readlines()]
            self.logger.info(
                f"length of subset_repos_file is: {len(subset_repos)} repos"
            )

            # review_files = []
            print(
                f"Currently processing {len(subset_repos)} repos' worth of PR Reviews data"
            )
            # gather PR-discussions filenames to process:
            discussions_review_files = self.multi_repo_PRCR_file_matcher(
                list_of_repos_to_match=subset_repos,
                out_filename="PR-issue-discussions_",
                matchstrings=[""],
                file_extension=".csv",
            )
            self.logger.info(
                f"discussions_review_files item consists of {len(discussions_review_files)}."
            )
            # gather main and sub PR CR filenames to process:
            main_sub_review_files = self.multi_repo_PRCR_file_matcher(
                list_of_repos_to_match=subset_repos,
                out_filename="all-PR-reviews_json",
                matchstrings=["_main-reviews__", "_sub-reviews__"],
                file_extension=".json",
            )
            self.logger.info(
                f"main_sub_review_files item consists of {len(main_sub_review_files)}."
            )

            review_files = (
                discussions_review_files + main_sub_review_files
            )  # important! This is the list of existing files matching subset repos which contain review info!

            self.logger.info(f"review_files item consists of {len(review_files)}.")

        reviews_data = pd.DataFrame()

        # JOIN THE DF CONTENT OF EACH REPO's PR REVIEWS INTO ONE MASSIVE DF

        for repofile in review_files:
            self.logger.info(f"Checking {repofile} for PR code reviews.")
            # for repofile in review_files:
            file = Path(repofile)
            # file = Path(self.data_location, repofile)
            if not file.exists():
                raise RuntimeError(
                    f"Error handling PR reviews data from file {file} via {repofile}. File doesn't exist"
                )
            self.logger.debug(f"Running on PR reviews file {file}.")
            # gather THIS repo's data

            reviews_data_next = self.process_format_PR_reviews(
                file,
            )
            print(
                f"{len(reviews_data_next) if reviews_data_next is not None else 'help'}"
            )
            # join this data to overall dataset from many repos
            reviews_data = pd.concat([reviews_data, reviews_data_next])

            self.logger.info(f"Generated df of {len(reviews_data)} review data.")

            assert reviews_data is not None, (
                "reviews_data type is None; something went wrong!"
            )

            filestr = f"merged_reviews_data_all_types_x{len(review_files)}-reviewfiles_{self.current_date_info}.csv"
            writeout_path = Path(self.data_location, filestr)

            try:
                # WRITE OUT THIS SUPER IMPORTANT DATA TO FILE!
                reviews_data.to_csv(path_or_buf=writeout_path, header=True, index=False)
                self.logger.info(
                    f"Saved reviews_data df for {len(review_files)} repos with {len(reviews_data)} devs to file: {filestr}"
                )

                return reviews_data

            except Exception as e:
                self.logger.error(
                    f"Error in attempting to write output file; {e}; error type: {type(e)}; writeout path attempted was: {writeout_path}"
                )
                raise

    def do_all_PR_reviews_handling(self, dataset_repos_list):
        runprreviews = RunPRReviews(
            in_notebook=self.in_notebook,
            logger=self.logger,
            config_path=self.config_path,
            out_filename=self.out_filename,  # "processed-PR-reviews",
        )

        self.logger.info("""The data collection steps for PR Code Review
                         interactions and Issue Ticket Discussions have 
                         been completed already and are not implemented 
                         in this workflow, however they can be run by 
                         enabling the function `run_get_reviews()`
                        """)
        # runprreviews.run_get_reviews(filepath=TODO) ##### THIS NEEDS FIXED TO TAKE INPUT FILE.

        try:
            reviews_data = runprreviews.format_many_repo_PR_reviews(
                subset_repos_file=dataset_repos_list
            )
        except Exception as e:
            self.logger.error(
                f"Encountered review-formatting workflow-borking error trying to read and process PR reviews files; error {e}"
            )
            exit(1)
        self.logger.info(
            "completed processing review files, resulting in 'reviews_data' df."
        )
        return reviews_data


# if __name__ == "__main__":
#     logger = loggit.get_default_logger(
#         console=True,
#         set_level_to="DEBUG",
#         log_name="logs/PR_reviews_workflow_logs.txt",
#         in_notebook=False,
#     )

#     logger.info("Running PR review data formatting.")

#     runprreviews = RunPRReviews(
#         in_notebook=False,
#         config_path="githubanalysis/config.cfg",
#         logger=logger,
#         out_filename="processed-PR-reviews",
#     )

#     logger.info("The data collection steps for PR Code Review interactions and Issue Ticket ")

#     try:
#         runprreviews.format_many_repo_PR_reviews()
#     except Exception as e:
#         logger.error(
#             f"Encountered review-formatting workflow-borking error trying to read and process PR reviews files; error {e}"
#         )
#         exit(1)
