"""Collate PR Code Review (PRCR) datafiles, generate dataframes ready for analysis and get timestamp and interaction types info for Pull Request Code Reviews (PRCR)."""

from pathlib import Path
import pandas as pd
import datetime
from githubanalysis.setup_classes import DatasetSetup


class PrepDataPRReviews(DatasetSetup):
    def _log_name(self) -> str:
        return "pre-analysis_data_PR_reviews_prep"

    def subset_by_dates(
        self,
        df: pd.DataFrame,
        datestamp_column=str,
        from_datestamp: datetime.datetime = datetime.datetime.min,  # default to earliest possible year - not sensible, but doesn't change behaviour :C
        to_datestamp: datetime.datetime = datetime.datetime.today(),  # defaults to today, which is the latest possible date, no behaviour changed.
    ):
        """
        There should be a function that subsets the reviews'
        interactions to between specific date/timestamps in a specific column
        to assist with future calculations and analysis.

        Assumes UTC timezone as this is the default GH timezone.
        """
        return df[
            (df[datestamp_column] > from_datestamp)
            & (df[datestamp_column] < to_datestamp)
        ]

    def calculate_RC_PRCR(self, reviews_df: pd.DataFrame) -> pd.DataFrame:
        """
        When given a dataframe of many repos' worth of PR CR (pull request code review)
        interactions all concatenated together, calculate what proportion of the
        total number of reviews present for a repo_name each repo-individual
        (unique repo_name + gh_username combo) is responsible for authoring.
        Return dataframe of per-repo-individual-data.
        """
        # isolate N of PR review interactions per repo via groupby:
        per_repo_info = (
            reviews_df.groupby(by=["repo_name"])
            .size()
            .reset_index(
                name="N_repo_reviews",
            )
        )
        # isolate repo-individuals' number of reviews:
        per_repo_individual_info = (
            reviews_df.groupby(by=["repo_name", "review_author_gh_username"])
            .size()
            .reset_index(
                name="N_reviews",
            )
        )

        # merge repo review-totals onto the per-repo-individuals' number of authored reviews, to create new df
        new_info = per_repo_individual_info.merge(per_repo_info).reset_index(drop=True)
        # calculate RC (repository contribution) of each repo-individual for PR CR (pull request code reviews)
        new_info["RC_PRCR"] = (new_info.N_reviews / new_info.N_repo_reviews) * 100
        return new_info

    def add_repo_association_info(self, reviews_df: pd.DataFrame) -> pd.DataFrame:
        """
        When passed reviews_df (many repos' worth of pull request code review
        interactions all concatenated together), pull out the repo_association information;
        return new ***per-repo-individual-df*** with new column "review_author_repo_association":
        a list of unique attached repo-associations that contributor has associated
        with their reviews for that repo.
        """
        return (
            reviews_df.groupby(["repo_name", "review_author_gh_username"])[
                "review_author_repo_association"
            ]
            .unique()
            .reset_index()
        )

    def process_PRCRs(
        self,
        sample_reviews_file_to_process: Path,
        # subset_repos_file: Path, # ideally add this feature in subsequently
        out_file_name: str,
    ):
        """
        Pull in collated reviews for all repos as SINGLE file generated by PRCR Workflow (sample_reviews_file_to_process).
        Collate repo-individuals' PR code reviews data; Write out repo-individuals' reviews data to csv
        Return repo-individuals'(devs) reviews data in data-per-dev format.
        """

        # load the df:
        self.logger.info(f"Attempting to load file {sample_reviews_file_to_process}")
        reviews_data_file = sample_reviews_file_to_process
        reviews_df = pd.read_csv(
            Path(reviews_data_file), header=0, low_memory=False, dtype=object
        )
        self.logger.info(f"reviews_df has shape {reviews_df.shape}")

        self.logger.info(
            f"There are {reviews_df.repo_name.nunique()} unique repo names in this PRCR / REVIEWS data set"
        )

        self.logger.info(
            f"There are {reviews_df.review_author_gh_username.nunique()} unique gh-usernames in this PRCR / REVIEWS data set"
        )  # 26146
        self.logger.info(
            f"There are {reviews_df.review_author_gh_id.nunique()} unique gh-username IDs in this PRCR / REVIEWS data set"
        )  # 27616

        self.logger.info(
            f"There are {len(reviews_df)} PR CR interactions in this PRCR / REVIEWS dataset"
        )
        self.logger.info(
            f"There are {reviews_df.review_type.nunique()} unique review types in this PRCR / REVIEWS data set"
        )  # 3
        self.logger.info(
            f"These {reviews_df.review_type.nunique()} unique review types are distrubuted like this: \n {reviews_df.review_type.value_counts(dropna=False)} \n\n {reviews_df.review_type.value_counts(dropna=False, normalize=True)}"
        )  # 3

        # calculate N of repo-individuals in the dataset:
        self.logger.info(
            f"There are {len(reviews_df.groupby(by=['repo_name', 'review_author_gh_username']).size())} repo-individuals in this dataset in total"
        )

        # create per-repo-individual(dev) df with RC PRCR!:
        per_repo_individual_data = self.calculate_RC_PRCR(reviews_df=reviews_df)
        ######### TODO: continue here #########
        # report stats on average RC_PRCR values across repos, in general, (and maybe by repo-association??)

        # add repo-association info:  # TODO: complete this
        per_repo_individual_data.merge(
            self.add_repo_association_info(
                reviews_df=reviews_df
            )  # returns df of repo_name, username, and list of repo-associations for that contributor across their reviews
        )
        # self.logger.info(f"There are {sum(new_info['review_author_repo_association'].apply(lambda x: len(x)) != 1)} repo-individuals with MORE THAN ONE REPO_ASSOCIATION listed")

        return per_repo_individual_data
