"""Reformat raw PR reviews json data from files into pd.DataFrames"""

import pandas as pd
import re
from pathlib import Path
import logging
from githubanalysis.setup_classes import LocationSetup


class ReviewsFormatter(LocationSetup):
    def _log_name(self) -> str:
        return "PR_reviews_reformatter_logs"

    def __init__(
        self,
        in_notebook: bool,
        logger: None | logging.Logger = None,
    ) -> None:
        super().__init__(
            in_notebook=in_notebook,
            logger=logger,
        )
        self.reformatted_PR_reviews = None
        self.repo_name = None
        self.sanitised_repo_name = None

    # def reformat_PR_nums_object(self, ):
    ## THIS WOULD FORMAT THE PR NUMBERS DETAILS CONTENT JSON INTO PD.DF; TO DO LATER
    #     pass

    def review_sorter(
        self,
        file_to_sort: Path,
    ) -> str:
        rev_file_type = ""
        if file_to_sort.match("all-PR-reviews_json_sub-reviews*"):
            rev_file_type = "sub"
        elif file_to_sort.match("all-PR-reviews_json_main-reviews*"):
            rev_file_type = "main"
        return rev_file_type

    def reformat_PR_reviews_object(
        self, reviews_type: str, PR_reviews_json_file: Path
    ) -> pd.DataFrame:
        """
        Function reads in json file of one repo's PR reviews data and pulls out relevant data into pd.DF
        Does NOT save out the DF.
        """

        assert reviews_type in ["sub", "main"], (
            f"'reviews_type' must be one of 'sub' or 'main' for correct handling but reviews_type is {reviews_type}"
        )

        rough_df = pd.read_json(PR_reviews_json_file)  # load in json from the file

        assert not rough_df.empty, (
            f"dataframe generated by loading json from file {PR_reviews_json_file} is empty..."
        )

        if reviews_type == "main":
            df_needs_these_colums_main = [
                "repo_name",  # not currently present at read-in of json, added subsequently in this script.
                "PR_review_id",
                "reviewed_PR_number",
                "review_PR_url",
                "review_author_gh_username",
                "review_author_gh_id",
                "author_review_date",
                "review_state",
                "review_body",
                "commit_id",
                "review_type",
                "API_links",
            ]

            rough_df = rough_df.rename(
                columns={
                    "id": "PR_review_id",
                    "user": "review_author_username",
                    "body": "review_body",
                    "state": "review_state",
                    "pull_request_url": "review_PR_url",
                    "author_association": "review_author_association",
                    "submitted_at": "author_review_date",
                    "commit_id": "commit_id",  # keep this same
                    "_links": "API_links",
                },
                errors="raise",
                inplace=False,
            )
            rough_df["review_type"] = "main"  # create column filled with text 'main'

        elif reviews_type == "sub":
            df_needs_these_colums_sub = [
                "repo_name",  # not currently present at read-in of json, added subsequently in this script.
                "PR_review_id",
                "reviewed_PR_number",
                "review_PR_url",
                "review_comment_url",
                "review_author_gh_username",
                "review_author_gh_id",
                "review_author_association",
                # "review_state", # no 'state' for subreviews
                "review_body",
                "commit_id",
                "main_PR_review_id",  # main PR CR this is a subreview to
                "author_review_date",
                "subsequent_author_review_date",
                "reply_to_subreview_id",
                "commit_id",
                "review_type",
                "API_links",
            ]

            rough_df = rough_df.rename(
                columns={
                    "id": "PR_review_id",  # in this case, the ID is the sub-review ID
                    "user": "review_author_username",
                    "body": "review_body",
                    "url": "review_comment_url",  # url for this review item
                    "pull_request_review_id": "main_PR_review_id",  # main PR CR this is a subreview to
                    "pull_request_url": "review_PR_url",  # url for the PR this review item
                    "author_association": "review_author_association",
                    "created_at": "author_review_date",  # using subreview created date, as there's no submitted_at for subreviews.
                    "updated_at": "subsequent_author_review_date",  # subreview updated (? future feat: consider counting this as a separate review interaction, esp if some time has passed? ?)
                    "in_reply_to_id": "reply_to_subreview_id",
                    "path": "file_reviewed",  # where the review applies to
                    "_links": "API_links",
                },
                errors="raise",
                inplace=False,
            )

            rough_df["review_type"] = (
                "subreview"  # create column filled with text 'subreview'
            )

        else:
            self.logger.error(
                "Encountered review-formatting function error trying to handle reviews_type for PR reviews file"
            )
            raise RuntimeError  # handle this error! oughtn't occur due to the assert at the start tho

        # add repo_name,
        rough_df["repo_name"] = rough_df.review_PR_url.map(
            lambda x: re.split(
                r"(\w+\/\w+)", x.replace("https://api.github.com/repos/", "")
            )[1]
        )
        self.repo_name = rough_df["repo_name"][0]
        self.sanitised_repo_name = self.repo_name.replace("/", "-")

        #  reformat user column to pull out login, pull PR number off PR_url,
        rough_df["reviewed_PR_number"] = rough_df.review_PR_url.map(
            lambda x: x.rsplit("/", 1)[1]
        )
        rough_df["review_author_gh_username"] = rough_df.review_author_username.map(
            lambda x: x.get("login", None)
        )
        rough_df["review_author_gh_id"] = rough_df.review_author_username.map(
            lambda x: x.get("id", None)
        )

        if reviews_type == "main":
            # match columns to df_needs_these_columns
            assert len(set(df_needs_these_colums_main) & set(rough_df.columns)) == len(
                set(df_needs_these_colums_main)
            ), (
                f"Dataframe columns do not match expected list for PR reviews for {PR_reviews_json_file}; current columns: {rough_df.columns}; expected columns: {df_needs_these_colums_main}."
            )
        elif reviews_type == "sub":
            # drop columns not in list...
            rough_df.drop(  # drop columns not in list method via: https://stackoverflow.com/a/56891565
                columns=[
                    col for col in rough_df if col not in df_needs_these_colums_sub
                ],
                inplace=True,
            )

            # match columns to df_needs_these_columns
            assert len(set(df_needs_these_colums_sub) & set(rough_df.columns)) == len(
                set(df_needs_these_colums_sub)
            ), (
                f"Dataframe columns do not match expected list for PR reviews for {PR_reviews_json_file}; current columns: {rough_df.columns}; expected columns: {df_needs_these_colums_sub}."
            )
        else:
            self.logger.error(
                "Encountered review-formatting function error trying to handle reviews_type for PR reviews file"
            )
            raise RuntimeError  # handle this error! oughtn't occur due to the assert at the start tho

        self.reformatted_PR_reviews = rough_df  # save processed df to reformatted_PR_reviews in class for reuse elsewhere

        return self.reformatted_PR_reviews

    # def reformat_PR_reviews_from_file(self, PR_reviews_file: str):
    #     """
    #     Reformat raw PR review data from json file into pd.DataFrame appropes format.
    #     """

    #     with open(PR_reviews_file, "r") as raw_PR_reviews_file:
    #         raw_reviews = json.load(raw_PR_reviews_file)

    #     return self.reformat_PR_reviews_object(raw_reviews)

    def save_formatted_PR_reviews(
        self, reviews_type: str, out_filename="processed-PR-reviews"
    ):
        """
        Save the reformatted PR reviews data out to csv file.
        """
        assert reviews_type in ["sub", "main"], (
            "'reviews_type' must be one of 'sub' or 'main' for correct handling."
        )

        write_out = f"{self.data_location / out_filename}_{reviews_type}_{self.sanitised_repo_name}_{self.current_date_info}.csv"

        if self.reformatted_PR_reviews is not None:
            self.reformatted_PR_reviews.to_csv(
                path_or_buf=write_out, mode="w", index=False, header=True
            )
            self.logger.info(
                f"wrote out dataframe of {reviews_type} PR reviews to file {write_out} for repo {self.repo_name}"
            )
        else:
            raise RuntimeError(
                f"Error: Failed saving reformatted {reviews_type} PR Reviews data out to {write_out}. Run reformat_PR_reviews*() function."
            )
