"""Reformat raw PR reviews json data fom files into pd.DataFrames"""

import pandas as pd
import re
from pathlib import Path
import logging
from githubanalysis.setup_classes import LocationSetup


class ReviewsFormatter(LocationSetup):
    def _log_name(self) -> str:
        return "PR_reviews_reformatter_logs"

    def __init__(
        self,
        in_notebook: bool,
        logger: None | logging.Logger = None,
    ) -> None:
        super().__init__(
            in_notebook=in_notebook,
            logger=logger,
        )
        self.reformatted_PR_reviews = None
        self.repo_name = None
        self.sanitised_repo_name = None

    # def reformat_PR_nums_object(self, ):
    ## THIS WOULD FORMAT THE PR NUMBERS DETAILS CONTENT JSON INTO PD.DF; TO DO LATER
    #     pass

    def reformat_PR_reviews_object(self, PR_reviews_json_file: Path) -> pd.DataFrame:
        """Function reads in json file of one repo's PR reviews data and pulls out relevant data into pd.DF"""
        rough_df = pd.read_json(PR_reviews_json_file)  # load in json from the file

        assert not rough_df.empty, f"dataframe generated by loading json from file {PR_reviews_json_file} is empty..."

        df_needs_these_colums = [
            "repo_name",
            "PR_review_id",
            "reviewed_PR_number",
            "review_author_gh_username",
            "review_author_gh_id",
            "author_review_date",
            "review_state",
            "review_body",
        ]

        rough_df = rough_df.rename(
            columns={
                "id": "PR_review_id",
                "user": "review_author_username",
                "body": "review_body",
                "state": "review_state",
                "pull_request_url": "review_PR_url",
                "author_association": "review_author_association",
                "submitted_at": "author_review_date",
            },
            errors="raise",
            inplace=False,
        )

        # add repo_name,
        rough_df["repo_name"] = rough_df.review_PR_url.map(
            lambda x: re.split(
                r"(\w+\/\w+)", x.replace("https://api.github.com/repos/", "")
            )[1]
        )
        self.repo_name = rough_df["repo_name"][0]
        self.sanitised_repo_name = self.repo_name.replace("/", "-")

        #  reformat user column to pull out login, pull PR number off PR_url,
        rough_df["reviewed_PR_number"] = rough_df.review_PR_url.map(
            lambda x: x.rsplit("/", 1)[1]
        )
        rough_df["review_author_gh_username"] = rough_df.review_author_username.map(
            lambda x: x.get("login", None)
        )
        rough_df["review_author_gh_id"] = rough_df.review_author_username.map(
            lambda x: x.get("id", None)
        )

        # match columns to df_needs_these_columns
        assert (
            len(set(df_needs_these_colums) & set(rough_df.columns))
            == len(set(df_needs_these_colums))
        ), f"Dataframe columns do not match expected list for PR reviews for {PR_reviews_json_file}; current columns: {rough_df.columns}; expected columns: {df_needs_these_colums}."

        self.reformatted_PR_reviews = rough_df  # save processed df to reformatted_PR_reviews in class for reuse elsewhere

        return self.reformatted_PR_reviews

    # def reformat_PR_reviews_from_file(self, PR_reviews_file: str):
    #     """
    #     Reformat raw PR review data from json file into pd.DataFrame appropes format.
    #     """

    #     with open(PR_reviews_file, "r") as raw_PR_reviews_file:
    #         raw_reviews = json.load(raw_PR_reviews_file)

    #     return self.reformat_PR_reviews_object(raw_reviews)

    def save_formatted_PR_reviews(self, out_filename="processed-PR-reviews"):
        """
        Save the reformatted PR reviews data out to csv file.
        """

        write_out = f"{self.data_location/out_filename}_{self.sanitised_repo_name}_{self.current_date_info}.csv"

        if self.reformatted_PR_reviews is not None:
            self.reformatted_PR_reviews.to_csv(
                path_or_buf=write_out, mode="w", index=True, header=True
            )
            self.logger.info(
                f"wrote out dataframe of PR reviews to file {write_out} for repo {self.repo_name}"
            )
        else:
            raise RuntimeError(
                f"Error: Failed saving reformatted PR Reviews data out to {write_out}. Run reformat_PR_reviews*() function."
            )
